#!/usr/bin/python2.7
# -*- coding: UTF-8 -*-
# Author: justzx <justzx2011@gmail.com>
#         lvzongting <lvzongting@gmail.com>
#	  needf <zy20130729@gmail.com>
# License: GNU LGPL3

__revision__ = 'beta'

if __name__=="__main__":
    import os
    os.system("python2.7 /usr/lib/openyoudao/openyoudao.py")
